name: rick_and_morty_demo
description: Rick And Morty Series Informations.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Network Helper
  dio: ^4.0.6
  # Json Helper
  json_annotation: ^4.4.0
  # State Management
  provider: ^6.0.2
  # Link Launcher
  url_launcher: ^6.0.20
  # Fonts
  google_fonts: ^2.3.1
  # Responsive Design Helper
  responsive_framework: ^0.1.7
  infinite_scroll_pagination: ^3.1.0
  vector_math: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Json Generator
  json_serializable: ^6.1.6

  flutter_lints: ^1.0.0
  # Generator Launchers
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
